language: cpp

compiler:
    - clang

os:
    - linux

addons:
  apt:
    sources:
        - llvm-toolchain-precise-3.8
    packages:
        - clang-3.8
        - gcc-multilib
        - flex
        - bison

install:
    - mkdir deps && cd deps
    - git clone git://git.savannah.gnu.org/grub.git && cd grub
    - ./autogen.sh 
    - ./configure 
    - make -j2
    - cd ../../
    - ln -s ./deps/grub/grub-mkrescue grub-mkrescue

script:
    make-j2

cache:
  apt: true