language: cpp

compiler:
    - clang

os:
    - linux

addons:
  apt:
    packages:
        - gcc-multilib
        - flex
        - bison

install:
    - mkdir deps && cd deps
    - git clone git://git.savannah.gnu.org/grub.git && cd grub
    - ./autogen.sh 
    - ./configure 
    - make -j2
    - cd ../../
    - PATH=$(pwd)/deps/grub/:$PATH
    - export PATH 

script:
    make -j2

cache:
  apt: true