language: cpp

compiler:
    - clang

os:
    - linux

env:
    matrix:
    - ARCH=i386
    - ARCH=x86_64

addons:
  apt:
    packages:
        - gcc-multilib
        - flex
        - bison
        - qemu
        - expect

install:
    - mkdir deps && cd deps
    - git clone git://git.savannah.gnu.org/grub.git && cd grub
    - ./autogen.sh 
    - ./configure 
    - make -j2
    - cd ../../
    - PATH=$(pwd)/deps/grub/:$PATH
    - export PATH 

script:
    make -j2 && expect test/test.expect

cache:
    apt: true