language: cpp
sudo: required
dist: trusty

compiler:
    - clang

os:
    - linux

env:
    matrix:
    - ARCH=i386
    - ARCH=x86_64

addons:
  apt:
    sources:
        - llvm-toolchain-precise-3.8
    packages:
        - gcc-multilib
        - flex
        - bison
        - qemu
        - expect
        - clang-3.8

install:
    - mkdir deps && cd deps
    - git clone git://git.savannah.gnu.org/grub.git && cd grub
    - ./autogen.sh 
    - ./configure 
    - make -j2
    - cd ../../
    - PATH=$(pwd)/deps/grub/:$PATH
    - export PATH 
    - export CC=clang-3.8
    - export CXX=clang++-3.8
script:
    make -j2  CC=clang-3.8 CXX=clang++-3.8 && test/is_multiboot.sh && expect test/test.expect

cache:
    apt: true